feat(exit): exit & cleanup on push error

diff --git a/src/clog b/src/clog
--- a/src/clog
+++ b/src/clog
@@ -85,6 +85,35 @@ function release {
   $SRC/$service release "$tag" "$name" "$branch" "$body"
 }
 
+# reset working branch in the event of failure
+function release-reset {
+  local chg="$1"
+  local pkg="$2"
+  local tag="$3"
+
+  # reset last commit
+  git reset --soft HEAD~1
+
+  # restore CHANGELOG.md & package.json
+  git restore --staged $chg
+  git restore --staged $pkg
+
+  # delete if untracked OR checkout latest version
+  [ -z "$($SRC/git untracked $chg)" ] && {
+    git checkout $chg;   # tracked
+  } || {
+    rm $chg;
+  }
+  [ -z "$($SRC/git untracked $pkg)" ] && {
+    git checkout $pkg   # tracked
+  } || {
+    rm $pkg;
+  }
+
+  # remove tag
+  git tag -d $tag
+}
+
 
 # Shepherd these functions.
 source $(dirname "${0}")/sheep; sheep "$@"
